@Host = http://localhost:5155

### USERS
# create user (zapamiętaj id, np. 1)
POST {{Host}}/Users
Content-Type: application/json

{ "userName": "martyna", "password": "123" }

GET {{Host}}/Users
GET {{Host}}/Users/1
PUT {{Host}}/Users/1
Content-Type: application/json

{ "userName": "marti", "password": "" }

DELETE {{Host}}/Users/1


### POSTS
# create post (użyj istniejącego userId)
POST {{Host}}/Posts
Content-Type: application/json

{ "title": "Hello", "body": "First post body", "userId": 1 }

GET {{Host}}/Posts
GET {{Host}}/Posts?title=Hel
GET {{Host}}/Posts?userId=1
GET {{Host}}/Posts/1

PUT {{Host}}/Posts/1
Content-Type: application/json

{ "title": "Edited", "body": "Updated body", "userId": 1 }

DELETE {{Host}}/Posts/1


### COMMENTS
# create comment (użyj istniejących userId i postId)
POST {{Host}}/Comments
Content-Type: application/json

{ "body": "Nice!", "userId": 1, "postId": 1 }

GET {{Host}}/Comments
GET {{Host}}/Comments?userId=1
GET {{Host}}/Comments?postId=1
GET {{Host}}/Comments/1

PUT {{Host}}/Comments/1
Content-Type: application/json

{ "body": "Edited comment" }

DELETE {{Host}}/Comments/1
